"""Parity test: Component C's generalized-Q decomposition == R netmeta.

netmeta::decomp.design gives the authoritative design-by-treatment Q split
(Q.total = Q.het within designs + Q.inc between designs) at the common-effect
model. This test reproduces those numbers from inconsistency_nma's decomposition
math at tau^2 = 0 (the apples-to-apples weights) to machine precision on the two
canonical multi-arm networks -- the same networks the engine is verified on.

Reference CSV generated by nma/verify/gen_decomp_reference.R (netmeta 3.6-1).
"""
import csv
import sys
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))            # nma/

from nma_core import Comparison           # noqa: E402
from inconsistency_nma import _subset_Q   # noqa: E402


def _decomp_fixed(comps):
    """Fixed-effect (tau^2=0) Q decomposition, matching netmeta decomp.design."""
    Q_total, df_total = _subset_Q(comps, tau2=0.0)
    studies = {}
    for c in comps:
        studies.setdefault(c.studlab, []).append(c)
    designs = {}
    for rows in studies.values():
        d = frozenset({c.t1 for c in rows} | {c.t2 for c in rows})
        designs.setdefault(d, []).extend(rows)
    Q_het = 0.0
    df_het = 0
    for rows in designs.values():
        if len({c.studlab for c in rows}) < 2:
            continue
        Qd, dfd = _subset_Q(rows, tau2=0.0)
        Q_het += Qd
        df_het += dfd
    return {"Q_total": Q_total, "df_total": df_total, "Q_het": Q_het,
            "df_het": df_het, "Q_inc": max(Q_total - Q_het, 0.0),
            "df_inc": max(df_total - df_het, 0)}


def _load(path):
    comps = []
    with open(path) as f:
        for r in csv.DictReader(f):
            comps.append(Comparison(r["studlab"], r["treat1"], r["treat2"],
                                    float(r["TE"]), float(r["seTE"])))
    return comps


def _reference():
    ref = {}
    with open(HERE.parent / "verify" / "decomp_reference.csv") as f:
        for row in csv.DictReader(f):
            ref[row["network"]] = row
    return ref


@pytest.mark.parametrize("name,path", [
    ("senn2013", HERE / "senn2013_input.csv"),
    ("smoking", HERE / "smoking_input.csv"),
])
def test_decomp_matches_netmeta(name, path):
    ref = _reference()[name]
    got = _decomp_fixed(_load(path))
    for key in ("Q_total", "Q_het", "Q_inc"):
        assert abs(got[key] - float(ref[key])) < 1e-9, (key, got[key], ref[key])
    for key in ("df_total", "df_het", "df_inc"):
        assert got[key] == int(ref[key]), (key, got[key], ref[key])
