// Build the transport-NMA + registry-publication-bias manuscript .docx from verified
// committed numbers. Truth-first: every table value is transcribed from the committed
// transport_nma JSON artifacts (aact_kappa*.json, h2h_result.json, tnma_result); figures
// are regenerated by make_tnma_figures.py. Edit THIS file (not the .md) for the .docx.
// Run: node manuscript/build_tnma_docx.js
const fs = require("fs");
const path = require("path");
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, ImageRun,
  AlignmentType, LevelFormat, HeadingLevel, BorderStyle, WidthType, ShadingType,
  PageNumber, Footer, VerticalAlign,
} = require("docx");

const DIR = __dirname;
const FIG = path.join(DIR, "figures_tnma");

// ---------- helpers ----------
const border = { style: BorderStyle.SINGLE, size: 1, color: "BBBBBB" };
const borders = { top: border, bottom: border, left: border, right: border };
const cellMargins = { top: 60, bottom: 60, left: 110, right: 110 };
function runs(text, opts = {}) { return [new TextRun({ text, ...opts })]; }
function P(text, opts = {}) {
  return new Paragraph({ spacing: { after: opts.after ?? 120, line: 276 },
    alignment: opts.align, children: Array.isArray(text) ? text : runs(text, opts) });
}
function H1(text) { return new Paragraph({ heading: HeadingLevel.HEADING_1, children: runs(text) }); }
function H2(text) { return new Paragraph({ heading: HeadingLevel.HEADING_2, children: runs(text) }); }
function bullet(text) {
  return new Paragraph({ numbering: { reference: "bullets", level: 0 },
    spacing: { after: 60 }, children: Array.isArray(text) ? text : runs(text) });
}
function refItem(text) {
  return new Paragraph({ numbering: { reference: "refs", level: 0 },
    spacing: { after: 40 }, children: Array.isArray(text) ? text : runs(text, { size: 18 }) });
}
function tableFrom(headerRow, dataRows, colWidths) {
  const total = colWidths.reduce((a, b) => a + b, 0);
  const mkCell = (txt, w, opts = {}) => new TableCell({
    borders, width: { size: w, type: WidthType.DXA }, margins: cellMargins,
    verticalAlign: VerticalAlign.CENTER,
    shading: opts.head ? { fill: "D5E8F0", type: ShadingType.CLEAR }
      : (opts.fill ? { fill: opts.fill, type: ShadingType.CLEAR } : undefined),
    children: [new Paragraph({ spacing: { after: 0 },
      children: runs(String(txt), { bold: !!opts.head || !!opts.bold, size: 16 }) })],
  });
  const rows = [];
  rows.push(new TableRow({ tableHeader: true,
    children: headerRow.map((h, i) => mkCell(h, colWidths[i], { head: true })) }));
  for (const r of dataRows) {
    rows.push(new TableRow({ children: r.map((c, i) => {
      const v = (c && typeof c === "object") ? c : { t: c };
      return mkCell(v.t, colWidths[i], { bold: v.bold, fill: v.fill });
    }) }));
  }
  return new Table({ width: { size: total, type: WidthType.DXA }, columnWidths: colWidths, rows });
}
function figure(file, caption, widthPx) {
  const data = fs.readFileSync(path.join(FIG, file));
  const w = data.readUInt32BE(16), h = data.readUInt32BE(20);
  const dispW = widthPx ?? 560;
  const dispH = Math.round(dispW * h / w);
  return [
    new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 120, after: 60 },
      children: [new ImageRun({ type: "png", data, transformation: { width: dispW, height: dispH },
        altText: { title: caption, description: caption, name: file } })] }),
    new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 160 },
      children: runs(caption, { italics: true, size: 17 }) }),
  ];
}
function captionP(label, rest) {
  return new Paragraph({ spacing: { before: 60, after: 100 },
    children: [new TextRun({ text: label, bold: true, size: 18 }), new TextRun({ text: rest, size: 18 })] });
}
const B = (t) => new TextRun({ text: t, bold: true });
const T = (t) => new TextRun({ text: t });

// ---------- content ----------
const children = [];

// Title block
children.push(new Paragraph({ spacing: { after: 120 }, children: runs(
  "Registry-informed publication-bias correction for network meta-analysis: external effect-inflation magnitude from the ClinicalTrials.gov registered-versus-published gap",
  { bold: true, size: 28 }) }));
children.push(P([new TextRun({ text: "Mahmood Ahmad", bold: true }), new TextRun({ text: "¹²", superScript: true })], { after: 40 }));
children.push(P([new TextRun({ text: "¹ ", size: 18 }), new TextRun({ text: "Royal Free Hospital, London, United Kingdom", size: 18 })], { after: 20 }));
children.push(P([new TextRun({ text: "² ", size: 18 }), new TextRun({ text: "Tahir Heart Institute, Rabwah, Pakistan", size: 18 })], { after: 40 }));
children.push(P([new TextRun({ text: "ORCID: 0000-0001-9107-3704. Correspondence: mahmood726@gmail.com.", size: 18 })], { after: 80 }));
children.push(P([new TextRun({ text: "Competing interests. ", bold: true, size: 18 }),
  new TextRun({ text: "The author is an honorary member of the editorial board of Synthēsis (former Editor-in-Chief) and had no role in the handling, peer review, or editorial decision-making for this manuscript; any submission would be handled independently by another editor of the journal.", size: 18 })], { after: 40 }));
children.push(P([new TextRun({ text: "Funding. ", bold: true, size: 18 }), new TextRun({ text: "None.", size: 18 })], { after: 40 }));
children.push(P([new TextRun({ text: "Companion papers. ", bold: true, italics: true, size: 18 }),
  new TextRun({ text: "AdaptShrink (univariate) and AdaptShrink-NMA share the netmeta-parity engine used here; this paper addresses a distinct problem — publication-bias correction in NMA from an external registry signal rather than the in-network funnel.", size: 18, italics: true })], { after: 120 }));

// Abstract
children.push(H1("Abstract"));
children.push(P([B("Background. "), T("Funnel-based publication-bias corrections (Egger/PET-PEESE, trim-and-fill, Copas–Shi, Henmi–Copas) are unreliable in network meta-analysis (NMA), where each treatment rests on only a handful of direct comparisons. We ask whether an external registry signal can supply what the in-network funnel cannot.")]));
children.push(P([B("Methods. "), T("We correct a placebo-relative basic contrast dₜ by κ·(1−λₜ), where λₜ is the drug class's ClinicalTrials.gov results-reporting integrity (results-posted ÷ registered; AACT 2026-04-12) and κ is a selection-magnitude scale. On a real diabetes HbA1c network (metadat dat.senn2013; 10 treatments, 26 studies, τ = 0.33, I² = 1%) and a matched-coverage known-truth simulation on its geometry, we benchmark the registry correction against PET-PEESE, trim-and-fill, and Henmi–Copas. We then estimate κ externally — no oracle, no in-network funnel — from the AACT registered-versus-published HbA1c effect gap: within each class we compare mean absolute HbA1c mean-difference of trials whose results reached the literature (PubMed linkage) against trials with posted results but no linkage.")]));
children.push(P([B("Results. "), T("The external registry correction (oracle magnitude) is the only method that reliably improves matched-coverage error under selection (ΔMCIW0 −0.118 at B=0.15, −0.306 at B=0.30) and is exactly inert at B=0; every internal funnel model fails — PET-PEESE over-corrects catastrophically (up to +0.68 every cell). The registered-versus-published gap validates the registry model with no oracle: the per-class effect gap rises with selection severity (Pearson r = 0.50 vs 1−λ). The frozen pooled external magnitude κ = 0.158 matches the oracle at B=0.15 (ΔMCIW0 −0.119 vs −0.118) and wins across all B ≥ 0.15 in both funnel regimes — converting the correction from direction-only to direction + calibrated magnitude.")]));
children.push(P([B("Limitations (honest residual). "), T("A fixed external κ over-corrects modestly at true B=0 (ΔMCIW0 +0.05) — the selection-presence question, orthogonal to magnitude. A static class λ cannot certify a specific estimate is unbiased. We show, not assert, that this residual is irreducible on a sparse network: the only in-data presence gate (pooled-network Egger) fires ≤4% regardless of true B, so gating removes the B=0 harm but also every B>0 win. The correction is recommended where selection is a priori expected.")]));
children.push(P([B("Conclusion. "), T("An external registry signal supplies both the direction and, for the first time, a calibrated magnitude for publication-bias correction in a network too sparse for internal funnel methods.")], { after: 160 }));

// 1 Introduction
children.push(H1("1. Introduction"));
children.push(P("Publication and outcome-reporting bias inflates apparent treatment benefit; correcting for it is standard in pairwise meta-analysis but remains difficult in network meta-analysis (NMA). The established correctors — Egger's regression and its PET-PEESE refinement, the Duval–Tweedie trim-and-fill, and the Copas-family selection models — all read the funnel: they infer selection from the association between study effect and study precision. In an NMA that association must be estimated per contrast, and a typical contrast rests on three-to-six direct studies. A funnel regression on six points has ruinous intercept variance; a Copas selection model is simply infeasible."));
children.push(P("The information a sparse network lacks internally exists externally. Trial registries record which studies were run, independent of which were published. ClinicalTrials.gov, via the Aggregate Analysis of ClinicalTrials.gov (AACT) database, additionally records which registered trials posted structured results — a mandate strengthened by the FDAAA Final Rule — and, through automatic PubMed linkage, which trials' results reached the published literature. This is exactly the raw material of the classic registered-versus-published discrepancy studies (Turner 2008; Rising 2008), which showed that trials favourable to the sponsored drug are preferentially and more prominently published."));
children.push(P("This paper makes that external signal operational for NMA. We (i) define a per-class selection-severity proxy from the registry's results-reporting rate; (ii) benchmark a registry-informed correction head-to-head against the internal funnel models on a real diabetes network and a matched-coverage simulation; and (iii) — the main contribution — estimate the previously-missing selection magnitude externally, from the AACT registered-versus-published HbA1c effect gap, and show it recovers the correct correction strength with no oracle. We report the one place the approach cannot help (distinguishing a genuinely unbiased estimate within a selection-prone class) and demonstrate why that limit is irreducible on a sparse network."));

// 2 Methods
children.push(H1("2. Methods"));
children.push(H2("2.1 The network and the engine"));
children.push(P("We use the diabetes network dat.senn2013 from the metadat package (Senn 2013): 26 trials of oral glucose-lowering agents, outcome = mean change in HbA1c (%), connected through placebo and active comparators. Arms are reduced to study-level pairwise mean-difference contrasts and fitted with a frequentist graph-theoretic random-effects NMA (Rücker 2012); ranking uses the P-score (Rücker & Schwarzer 2015). The engine reproduces netmeta to ~1e-11. The fitted network has 10 treatments, 27 contrasts, τ = 0.33, I² = 1%, and reproduces the known ordering (rosiglitazone / pioglitazone / metformin most effective, sulfonylurea least)."));
children.push(H2("2.2 Registry selection-severity λ (direction)"));
children.push(P("For each drug class c we compute the results-reporting integrity ratio λc = (registered T2DM trials naming class c that posted results) ÷ (registered T2DM trials naming class c), from the AACT 2026-04-12 snapshot. A low λc means many trials of that class were registered but never posted results — a class-level fingerprint of reporting selection. We use (1 − λc) as the per-treatment selection-severity proxy. Observed values range from λ = 0.20 (α-glucosidase inhibitors) to λ = 0.48 (DPP-4 inhibitors)."));
children.push(H2("2.3 The correction"));
children.push(P("A placebo-relative basic contrast is shrunk toward the null in proportion to its class's severity: dₜ(corrected) = dₜ · (1 − κ·(1 − λₜ)), with an optional registry-informed variance inflation 1/√λₜ so the interval widens honestly for selection-prone classes. κ is the selection-magnitude scale, common across the network. The entire contribution of §2.5 is to estimate κ externally rather than assume it."));
children.push(H2("2.4 Truth-gate"));
children.push(P("We inject a known class-selection bias into each active treatment's true placebo-relative effect, dₜ(observed) = dₜ(true) · (1 + B·(1 − λₜ)), sweeping the unknown true strength B ∈ {0, 0.15, 0.263, 0.30}, and ask whether the correction recovers the true contrasts better than the unadjusted NMA. The metric is MCIW0 — twice the 95th percentile of |estimate − truth| across all (replicate × treatment) cells — with a paired bootstrap (3,000 resamples) CI on ΔMCIW0 vs the unadjusted baseline; a robust win requires the 97.5% CI upper limit below zero. Two selection geometries are scored: Regime A, a uniform multiplicative bias (SE-orthogonal, funnel-invisible), and Regime B, the same per-treatment magnitude distributed as a small-study effect (funnel-visible). Regime B is the geometry internal funnel methods are designed for; Regime A is the geometry registry selection actually produces."));
children.push(H2("2.5 External magnitude from the registered-versus-published gap"));
children.push(P("We estimate κ externally, with no oracle and no in-network funnel, using the logic of Turner (2008) inside the registry. Whether a trial's results reached the published literature is observable through PubMed linkage (study_references.reference_type ∈ {DERIVED, RESULT} → a PMID citing the trial's NCT number). We split each class's trials into published (a linkage exists) and registered-only (results posted, no linkage). If publication favours larger effects, the published subset should show a larger treatment effect."));
children.push(P("Endpoint and scale are held fixed to match the network: we extract HbA1c mean-difference analyses (outcome_analyses where param_type contains \"mean difference\"), normalise IFCC mmol/mol to NGSP % (a difference × 0.0915), and discard implausible |MD| > 5% (scale-coding errors). For each class c with adequate support we compute κ_MD(c) = mean|MD|_published ÷ mean|MD|_registered-only − 1. Two frozen, deployable summaries are formed before any simulation scoring: κ_pooled, the n-weighted mean of max(0, κ_MD(c)) over adequately-powered classes (a per-node effect-inflation scale), and κ_slope, the WLS slope of κ_MD(c) on (1 − λc) through the origin (an external estimate of B). Adequate support = min(n_published, n_registered-only) ≥ 8."));
children.push(H2("2.6 Software and reproducibility"));
children.push(P("All analyses are Python (NumPy/SciPy/pandas/DuckDB) on the committed netmeta-parity engine. Scripts: class_lambda.py (λ), aact_kappa.py → aact_kappa_freeze.py (external κ, frozen), tnma.py and h2h_bench.py (head-to-head), aact_kappa_truthgate.py (external-κ truth-gate). Regression tests in test_aact_kappa.py (4/4) guard the frozen numbers and the headline win. Every value in this manuscript is transcribed from a committed JSON artifact."));

// 3 Results
children.push(H1("3. Results"));
children.push(H2("3.1 The real network and correction"));
children.push(P("On dat.senn2013 the registry overlay shrinks each active treatment's apparent benefit in proportion to its class's severity (Table 1). Rosiglitazone's placebo-relative HbA1c effect moves from −1.23% to −0.88% (TZD, λ = 0.42); the α-glucosidase inhibitors move most (λ = 0.20). Benfluorex, which has no registered drug class, is left unadjusted (λ ≡ 1). This is the qualitative behaviour a registry correction should have; §3.3–3.5 test it quantitatively."));

children.push(captionP("Table 1. ", "Real dat.senn2013 network with the registry overlay (κ = 0.5 illustrative): MD vs placebo, SE, P-score, class, registry λ, registry-adjusted MD. Source: tnma.py / tnma_result.txt."));
children.push(tableFrom(
  ["treatment", "MD vs plac", "seTE", "P-score", "class", "λ", "reg-adj MD"],
  [
    ["rosiglitazone", "−1.233", "0.128", "0.894", "TZD", "0.42", "−0.876"],
    ["pioglitazone", "−1.129", "0.220", "0.775", "TZD", "0.42", "−0.802"],
    ["metformin", "−1.127", "0.154", "0.782", "metformin", "0.40", "−0.789"],
    ["miglitol", "−0.950", "0.232", "0.614", "AGI", "0.20", "−0.570"],
    ["acarbose", "−0.842", "0.245", "0.520", "AGI", "0.20", "−0.505"],
    ["benfluorex", "−0.731", "0.286", "0.436", "(none)", "1.00", "−0.731"],
    ["vildagliptin", "−0.700", "0.353", "0.423", "DPP4", "0.48", "−0.518"],
    ["sitagliptin", "−0.570", "0.354", "0.333", "DPP4", "0.48", "−0.422"],
    ["sulfonylurea", "−0.417", "0.241", "0.210", "SU", "0.47", "−0.305"],
  ], [1700, 1180, 900, 1080, 1500, 800, 1300]));
children.push(P("", { after: 120 }));

children.push(H2("3.2 The registered-versus-published gap validates the registry model — with no oracle"));
children.push(P("Across 464 HbA1c mean-difference analyses, published trials report a larger absolute HbA1c effect than registered-only trials in the well-supported classes: metformin +0.08, SGLT2 +0.29, DPP-4 +0.21, α-glucosidase +0.35 (Table 2). Critically, the gap grows with registry selection severity: κ_MD(c) correlates with (1 − λc) at Pearson r = 0.50, and its through-origin regression slope is 0.26 (Figure 1). This is an external, oracle-free confirmation that the registry λ ranks selection severity in the same direction as the actual published-effect inflation — the assumption the correction rests on, now supported by independent data. The frozen scales are κ_pooled = 0.158 and κ_slope = 0.263. Small-n classes are excluded (e.g. sulfonylurea has only 3 registered-only analyses, producing an implausible −0.64 driven by one large value)."));

children.push(captionP("Table 2. ", "AACT registered-versus-published HbA1c effect gap per class (T2DM; 464 mean-difference analyses). |MD| = mean absolute HbA1c mean difference (NGSP %); κ_MD = published/registered-only − 1. min(n) < 8 (bold) excluded from the frozen estimate. Source: aact_kappa.json."));
children.push(tableFrom(
  ["class", "n pub", "n reg-only", "|MD| pub", "|MD| reg-only", "κ_MD", "used"],
  [
    ["metformin", "101", "21", "0.453", "0.420", "+0.079", "yes"],
    ["SGLT2", "66", "24", "0.622", "0.483", "+0.289", "yes"],
    ["DPP4", "98", "79", "0.465", "0.384", "+0.210", "yes"],
    ["GLP1", "135", "18", "0.871", "0.871", "+0.000", "yes"],
    ["TZD", "34", "16", "0.527", "0.532", "−0.008", "yes"],
    ["insulin", "69", "14", "0.389", "0.391", "−0.004", "yes"],
    ["AGI", "10", "48", "0.471", "0.349", "+0.349", "yes"],
    ["SU", "35", { t: "3", bold: true }, "0.412", "1.157", "−0.644", { t: "no", bold: true }],
  ], [1500, 900, 1300, 1200, 1500, 1160, 900]));
children.push(P([new TextRun({ text: "Frozen external estimates: κ_pooled = 0.158, κ_slope = 0.263, corr(κ_MD, 1−λ) = +0.50.", italics: true, size: 18 })], { after: 120 }));
children.push(...figure("fig1_corr_validation.png", "Figure 1. External validation with no oracle: per-class published-minus-registered HbA1c effect gap κ_MD against registry selection severity (1 − λ). Blue = adequately-powered classes (used); grey = excluded (sulfonylurea, n_reg = 3). Red line = through-origin WLS slope = external B̂ = 0.26; Pearson r = 0.50."));

children.push(H2("3.3 Head-to-head: external registry-λ beats every internal funnel model"));
children.push(P("On the simulation, each internal corrector is applied network-consistently — it estimates a per-treatment bias from that treatment's direct placebo-relative studies and subtracts it from the same league estimate the registry method adjusts, so methods differ only in how they estimate the bias (Table 3). The registry-λ correction (oracle magnitude) is the only reliable winner: ΔMCIW0 −0.118 (B=0.15) and −0.306 (B=0.30) in Regime A, and −0.097 / −0.222 in Regime B, exactly inert at B=0. PET-PEESE over-corrects catastrophically (+0.58 to +0.68 in every cell, both regimes), because a per-treatment funnel regression on three-to-six studies has enormous intercept variance — even in Regime B where it is correctly specified. Trim-and-fill and Henmi–Copas are inert-to-harmful; Copas–Shi is infeasible on the network. The registry λ is an external, near-zero-sampling-variance direction-of-selection signal the internal methods cannot recover from a handful of studies."));

children.push(captionP("Table 3. ", "Head-to-head vs internal funnel selection models (Regime A, matched-coverage ΔMCIW0 vs unadjusted NMA; negative = win). Source: h2h_result.json."));
children.push(tableFrom(
  ["method", "B = 0", "B = 0.15", "B = 0.30"],
  [
    [{ t: "registry-λ (oracle κ)", bold: true }, "+0.000 (tie)", { t: "−0.118 (WINS)", bold: true }, { t: "−0.306 (WINS)", bold: true }],
    [{ t: "registry-λ (external κ=0.158, deployable)", bold: true }, "+0.053 (HARMS)", { t: "−0.119 (WINS)", bold: true }, { t: "−0.231 (WINS)", bold: true }],
    ["PET-PEESE", "+0.680 (HARMS)", "+0.641 (HARMS)", "+0.577 (HARMS)"],
    ["trim-and-fill", "+0.035 (HARMS)", "+0.021 (HARMS)", "+0.024 (HARMS)"],
    ["Henmi–Copas", "+0.020 (HARMS)", "+0.002 (tie)", "−0.004 (tie)"],
    ["Copas–Shi", { t: "infeasible (needs k ≫ 6/treatment)", }, "—", "—"],
  ], [3200, 2000, 2080, 2080]));
children.push(P([new TextRun({ text: "The deployable external κ (frozen 0.158, no oracle) is shown alongside the oracle: at B = 0.15 it matches the oracle (−0.119) and at B = 0.30 wins (−0.231), beating every internal funnel model; its only cost is the B = 0 over-correction (+0.053). The head-to-head win therefore holds for the method a user can actually run.", size: 18 })], { after: 60 }));
children.push(P("", { after: 120 }));
children.push(...figure("fig2_headtohead.png", "Figure 2. Head-to-head ΔMCIW0 (95% paired-bootstrap CI) of the external registry-λ correction vs PET-PEESE, trim-and-fill, and Henmi–Copas at B = 0.15 and B = 0.30 (Regime A). Negative wins; PET-PEESE is off-scale harmful."));

children.push(H2("3.4 The external magnitude recovers the correction strength"));
children.push(P("Replacing the oracle with the frozen external κ (§2.5) is the decisive test (Table 4, Figure 3). The pooled external magnitude κ = 0.158 matches the oracle at B=0.15 — ΔMCIW0 −0.119 vs oracle −0.118 (Regime A) and −0.098 vs −0.097 (Regime B) — and wins across every B ≥ 0.15 in both regimes. It decisively beats the naive fixed κ = 0.5, which harms at B=0 by +0.42 and needs B ≥ 0.30 merely to help. The slope estimate κ = 0.263 matches the oracle exactly at B=0.263 by construction and wins for B ≥ 0.15. The correction is thus, for the first time, direction + calibrated magnitude: external registry data supplied the strength the sparse network could not."));

children.push(captionP("Table 4. ", "External-κ truth-gate (frozen AACT magnitude; matched-coverage ΔMCIW0 vs unadjusted NMA). Egger fire-rate = fraction of replicates the pooled-network presence gate fires. Source: aact_kappa_truthgate_result.json."));
children.push(tableFrom(
  ["true B", "oracle (=B)", "ext_pooled (0.158)", "ext_slope (0.263)", "fixed 0.5", "ext_pooled+gate", "Egger fire"],
  [
    ["0.00 (A)", "+0.000 tie", { t: "+0.053 HARMS", bold: true }, "+0.145 HARMS", "+0.416 HARMS", "+0.003 tie", "0.04"],
    ["0.15 (A)", "−0.118 WINS", { t: "−0.119 WINS", bold: true }, "−0.071 WINS", "+0.200 HARMS", "−0.000 tie", "0.02"],
    ["0.263 (A)", "−0.255 WINS", "−0.212 WINS", "−0.255 WINS", "−0.020 tie", "−0.003 tie", "0.01"],
    ["0.30 (A)", "−0.306 WINS", "−0.231 WINS", "−0.308 WINS", "−0.096 WINS", "−0.002 tie", "0.01"],
    ["0.15 (B)", "−0.097 WINS", { t: "−0.098 WINS", bold: true }, "−0.036 WINS", "+0.241 HARMS", "+0.000 tie", "0.01"],
    ["0.30 (B)", "−0.222 WINS", "−0.202 WINS", "−0.235 WINS", "+0.017 tie", "+0.000 tie", "0.00"],
  ], [1120, 1560, 1620, 1560, 1360, 1560, 940]));
children.push(P("", { after: 120 }));
children.push(...figure("fig3_truthgate.png", "Figure 3. Frozen external κ truth-gate: ΔMCIW0 vs true B for the oracle (upper bound), the frozen κ_pooled = 0.158, the naive fixed κ = 0.5, and the Egger-gated variant (Regime A). κ_pooled tracks the oracle at plausible B and over-corrects only mildly at B = 0; the gated variant is inert everywhere (the presence-gate limit)."));

children.push(H2("3.5 The honest residual: presence, not magnitude — and why it is irreducible here"));
children.push(P("A fixed external κ still over-corrects at true B=0 (κ_pooled +0.053, κ_slope +0.145; Table 4). This is not a magnitude error but the orthogonal selection-presence question: a static class-level λ cannot certify that a particular estimate within a selection-prone class happens to be unbiased. Only in-data evidence could, so we added the only such gate available — a pooled-network Egger test across all placebo-relative direct contrasts (pooling across treatments for power the per-contrast funnel lacks), applying the external κ only when |t| ≥ 1.64. Its fire-rate is 0.00–0.04 regardless of true B (Table 4, right column): it is blind in Regime A (registry selection is SE-orthogonal by construction) and underpowered in Regime B (≈ 20 studies, 4–6 per treatment). Gating therefore removes the B=0 over-correction but also removes every B > 0 win — the gated estimator ties the unadjusted NMA everywhere. This demonstrates, rather than asserts, that the presence question is irreducible on a network this sparse."));

children.push(H2("3.6 Generalisation to a second real network (depression, log-odds scale)"));
children.push(P("To test the method beyond diabetes we applied it end-to-end to a second, independent real network in a different domain and effect scale: dat.linde2015 (metadat), 66 antidepressant RCTs for major depression with arms grouped by class (SSRI, SNRI, TCA, atypical [NaSSa/SARI], MAOI [rMAO-A], plus NRI and Hypericum), outcome = treatment response, reduced to pairwise log-odds-ratio contrasts and fitted with the same engine. The network is sensible (9 treatments, 59 studies, τ = 0.18, I² = 0%; Hypericum/SNRI/TCA/SSRI all beat placebo, OR ≈ 1.7–1.9). We overlaid the real depression-class registry λ and applied the diabetes-frozen external κ = 0.158 as a cross-domain transfer test. On the truth-gate (Table 5), the registry corrections again beat every internal funnel model — PET-PEESE is catastrophic (ΔMCIW0 ≈ +1.2 at every B, worse than on diabetes because log-OR contrasts on few studies are even noisier); trim-and-fill harms; Henmi–Copas is inert. The oracle wins at B ≥ 0.15 and is exactly inert at B = 0, and the diabetes-frozen κ transfers: it improves matched-coverage error at every B, including a mild B = 0 gain (−0.042). That B = 0 behaviour is the reverse of diabetes (+0.05 cost) and is a network-specific bias–variance effect — here the low-λ classes also happen to have small placebo-relative effects, so registry-prescribed shrinkage toward the null reduces tail error rather than adding bias; the oracle remains exactly inert as designed. The core claims — registry beats internal funnel methods, PET catastrophic, external κ deployable and transferable — reproduce on a second real network."));
children.push(captionP("Table 5. ", "Truth-gate on the second real network (dat.linde2015, response log-OR; matched-coverage ΔMCIW0 vs unadjusted NMA). 'ext (diab κ=0.158)' applies the diabetes-frozen external magnitude to the depression network (cross-domain transfer). Source: linde_nma_result.json."));
children.push(tableFrom(
  ["true B", "oracle", "ext (diab κ=0.158)", "fixed κ=0.5", "PET", "TF", "HC"],
  [
    ["0.00", "+0.000 tie", { t: "−0.042 WINS", bold: true }, "−0.025 tie", "+1.224 HARMS", "+0.044 HARMS", "+0.000 tie"],
    ["0.15", "−0.062 WINS", { t: "−0.065 WINS", bold: true }, "−0.088 WINS", "+1.195 HARMS", "+0.024 HARMS", "+0.000 tie"],
    ["0.30", "−0.133 WINS", { t: "−0.084 WINS", bold: true }, "−0.146 WINS", "+1.174 HARMS", "+0.046 HARMS", "+0.000 tie"],
  ], [1080, 1480, 1720, 1440, 1360, 1300, 980]));
children.push(P("", { after: 120 }));

// 4 Discussion
children.push(H1("4. Discussion"));
children.push(P([B("What is new. "), T("Publication-bias correction in NMA has lacked a usable magnitude: the internal funnel is too noisy on a few studies per contrast (confirmed here by PET-PEESE's catastrophic failure and by a companion internal-κ̂ experiment that also failed). This paper supplies the magnitude from outside the network, using the registry's own record of which trials were published. The registered-versus-published effect gap both validates the severity ordering (no oracle; r = 0.50) and calibrates the strength (κ_pooled matches the oracle at plausible selection levels).")]));
children.push(P([B("Definitions and denominators (confidence flags). "), T("\"Published\" is operationalised as a PubMed linkage in AACT (DERIVED or RESULT reference type); \"registered-only\" as posted results without such a linkage. This is a conservative, noisy proxy for the Turner/Rising contrast: DERIVED links are auto-generated, so some genuinely published trials without an added citation fall into \"registered-only\", attenuating the gap toward zero — the true selection magnitude is therefore at least as large as reported. Denominators are modest (464 analyses; per-class published n = 34–135, registered-only n = 3–79), so per-class κ_MD is used only where min(n) ≥ 8 and the deployed estimate is the pooled scale, not per-class values. Sulfonylurea (n_reg = 3) is flagged and excluded. All effects are absolute mean differences on a common NGSP-% scale; direction is not used, so the estimate is a magnitude, not a signed effect.")]));
children.push(P([B("Deployment rule. "), T("Apply κ_pooled·(1 − λₜ) where selection is a priori expected — a selection-prone class flagged by a low registry λ — where the correction is oracle-matching. Accept the bounded +0.05 MCIW0 over-correction as the honest cost of operating without a presence gate. Do not apply it as a blanket adjustment to networks with no prior reason to suspect selection.")]));
children.push(P([B("Generalisation. "), T("The core results are not diabetes-specific: they reproduce on a second real network in a different domain and effect scale (depression, response log-odds; §3.6), where the registry corrections again beat every internal funnel model, PET-PEESE is again catastrophic, and the diabetes-frozen external κ transfers as a beneficial correction. The external validation (published-versus-registered gap tracking registry severity) also reproduces in the antidepressant domain on a scale-invariant measure.")]));
children.push(P([B("Transportability to a target population. "), T("A separate layer standardises the network to a defined target population via an external covariate (e.g. World Bank diabetes prevalence) using g-computation (Dahabreh 2020). In our known-truth simulations this layer is exactly inert when the target equals the donor pool and wins at a far target once a real effect-modifier exists, but dat.senn2013 carries no per-trial population covariate, so we make no real-data transportability claim here; it is reported as scoped simulation only.")]));
children.push(P([B("Second-domain replication (antidepressants). "), T("We tested endpoint-generalisation directly in Turner's own domain (major depression). Raw AACT HAM-D mean differences do not transfer — but this is a scale artefact, not a real boundary: raw HAM-D mixes 17/21/24-item versions, within- vs between-arm, and timepoints (41% have |MD| < 0.5, implausible), so the ratio reflects scale heterogeneity. Re-run on scale-invariant measures the gap reproduces. On the standardised significance measure z = |MD|/SE (HAM-D + MADRS), corr(κ_z, 1−λ) = +0.64 over the three adequately-powered classes (diabetes reference +0.50), and trial-level bootstrap shows published trials have robustly larger standardised effects in the two best-powered classes (SSRI κ_z +0.69 [+0.23, +1.29]; atypical +1.18 [+0.73, +1.86]; both exclude 0), while the lowest-severity class SNRI is null (−0.33 [−0.55, +0.26]) — consistent with the severity-tracking model. On response/remission log-odds the SSRI gap is also robustly positive (+0.47 [+0.09, +1.14]). We do not over-claim: only 2–3 antidepressant classes carry adequate registered-only support, so the class-level correlation is suggestive, not inferential; the robust evidence is the per-class trial-level gaps. Diabetes (7 classes) remains the primary validation; antidepressants corroborate it in a second, independent domain.")]));
children.push(P([B("Limitations. "), T("(i) The external-magnitude construction is endpoint-matched, so generalisation requires re-estimating κ on a standardised effect scale per endpoint family (raw multi-version rating scales must first be reduced to z or a log-odds effect, as above). (ii) The simulation uses the senn2013 geometry with an assumed multiplicative selection model; the oracle is an upper bound, not a claim about real senn2013 selection. (iii) λ and κ are drug-class properties from a single AACT snapshot; a live pipeline should re-freeze both per snapshot. (iv) The presence-gate limitation is intrinsic to sparse networks, not to this estimator.")]));

// 5 Conclusion
children.push(H1("5. Conclusion"));
children.push(P("For networks too sparse for internal funnel methods, a trial registry supplies both the direction and — via the registered-versus-published effect gap — a calibrated magnitude for publication-bias correction. The external magnitude matches an oracle at realistic selection levels and beats every internal selection model, while the one residual (distinguishing an unbiased estimate within a selection-prone class) is shown to be irreducible on a sparse network rather than a defect of the method."));

// References
children.push(H1("References"));
const REFS = [
  "Senn S, Gavini F, Magrez D, Scheen A. Issues in performing a network meta-analysis. Stat Methods Med Res. 2013;22(2):169–189.",
  "Rücker G. Network meta-analysis, electrical networks and graph theory. Res Synth Methods. 2012;3(4):312–324.",
  "Rücker G, Schwarzer G. Ranking treatments in frequentist network meta-analysis works without resampling methods. BMC Med Res Methodol. 2015;15:58.",
  "Egger M, Davey Smith G, Schneider M, Minder C. Bias in meta-analysis detected by a simple, graphical test. BMJ. 1997;315(7109):629–634.",
  "Stanley TD, Doucouliagos H. Meta-regression approximations to reduce publication selection bias. Res Synth Methods. 2014;5(1):60–78.",
  "Duval S, Tweedie R. A nonparametric \"trim and fill\" method of accounting for publication bias in meta-analysis. J Am Stat Assoc. 2000;95(449):89–98. (Companion: Biometrics. 2000;56(2):455–463.)",
  "Henmi M, Copas JB. Confidence intervals for random effects meta-analysis and robustness to publication bias. Stat Med. 2010;29(29):2969–2983.",
  "Copas J, Shi JQ. Meta-analysis, funnel plots and sensitivity analysis. Biostatistics. 2000;1(3):247–262.",
  "Turner EH, Matthews AM, Linardatos E, Tell RA, Rosenthal R. Selective publication of antidepressant trials and its influence on apparent efficacy. N Engl J Med. 2008;358(3):252–260.",
  "Rising K, Bacchetti P, Bero L. Reporting bias in drug trials submitted to the Food and Drug Administration: review of publication and presentation. PLoS Med. 2008;5(11):e217.",
  "Tasneem A, Aberle L, Ananth H, et al. The database for aggregate analysis of ClinicalTrials.gov (AACT) and subsequent regrouping by clinical specialty. PLoS ONE. 2012;7(3):e33677.",
  "Zarin DA, Tse T, Williams RJ, Carr S. Trial Reporting in ClinicalTrials.gov — the Final Rule. N Engl J Med. 2016;375(20):1998–2004.",
  "Dahabreh IJ, Robertson SE, Steingrimsson JA, Stuart EA, Hernán MA. Extending inferences from a randomized trial to a new target population. Stat Med. 2020;39(14):1999–2014.",
  "Vevea JL, Hedges LV. A general linear model for estimating effect size in the presence of publication bias. Psychometrika. 1995;60(3):419–435.",
];
REFS.forEach(r => children.push(refItem(r)));
children.push(P([new TextRun({ text: "Reference identifiers independently verified via PubMed / venue; see CITATION_CHECK_TNMA.md.", italics: true, size: 17 })], { after: 40 }));

// ---------- document ----------
const doc = new Document({
  creator: "Mahmood Ahmad",
  title: "Registry-informed publication-bias correction for NMA",
  styles: {
    default: { document: { run: { font: "Calibri", size: 21 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 28, bold: true, font: "Calibri", color: "1F3864" },
        paragraph: { spacing: { before: 260, after: 140 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 23, bold: true, font: "Calibri", color: "2E5496" },
        paragraph: { spacing: { before: 180, after: 100 }, outlineLevel: 1 } },
    ],
  },
  numbering: {
    config: [
      { reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "•",
        alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 460, hanging: 260 } } } }] },
      { reference: "refs", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.",
        alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 420, hanging: 300 } } } }] },
    ],
  },
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 },
      margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: "Registry-informed pub-bias correction for NMA  —  Page ", size: 16 }),
        new TextRun({ children: [PageNumber.CURRENT], size: 16 })] })] }) },
    children,
  }],
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync(path.join(DIR, "Transport_NMA.docx"), buf);
  console.log("wrote Transport_NMA.docx (" + buf.length + " bytes)");
});
