"""Robustness of the external magnitude to the 'published' DEFINITION.

The whole external-kappa result rests on how we split trials into 'published' vs 'registered-only'.
The main analysis uses PubMed linkage via study_references.reference_type in {DERIVED, RESULT}. DERIVED
links are auto-generated by NLM (a publication cites the NCT); RESULT links are sponsor-added result
citations. A reviewer will ask whether kappa_pooled=0.158 and corr(kappa_MD,1-lambda)=+0.50 survive a
stricter or looser definition. We recompute both under three definitions and report stability.

Definitions of 'published':
  both     = DERIVED or RESULT  (main analysis)
  result   = RESULT only        (stricter: sponsor-curated results publication)
  derived  = DERIVED only        (NLM auto-linkage)
Everything else (HbA1c record extraction, class assignment, min-n>=8 gate) is identical to aact_kappa.py.
"""
import duckdb, json, io, sys
import numpy as np
from pathlib import Path
try:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
except Exception:
    pass

A = r"F:\AACT-storage\AACT\2026-04-12"
HERE = Path(__file__).resolve().parent
LAM = json.load(open(Path(r"F:\ubcma\borrowing\class_lambda.json")))
con = duckdb.connect()


def t(n):
    return f"read_csv('{A}/{n}.txt', delim='|', header=true, quote='', ignore_errors=true, auto_detect=true, all_varchar=true)"


CLASSES = {
    'metformin': ['metformin'], 'SGLT2': ['gliflozin'], 'DPP4': ['gliptin'],
    'GLP1': ['glutide', 'exenatide', 'liraglutide', 'dulaglutide', 'semaglutide', 'lixisenatide', 'tirzepatide'],
    'SU': ['glipizide', 'glimepiride', 'glyburide', 'gliclazide', 'glibenclamide', 'sulfonylurea'],
    'TZD': ['glitazone', 'pioglitazone', 'rosiglitazone'], 'insulin': ['insulin'],
    'AGI': ['acarbose', 'miglitol', 'voglibose'], 'glinide': ['repaglinide', 'nateglinide'],
}
con.execute(f"""CREATE TEMP TABLE t2dm AS SELECT DISTINCT nct_id FROM {t('conditions')}
 WHERE lower(name) LIKE '%type 2 diabetes%' OR lower(name) LIKE '%type ii diabetes%';""")
res_set = set(r[0] for r in con.execute(f"SELECT DISTINCT nct_id FROM {t('study_references')} WHERE reference_type='RESULT' AND pmid IS NOT NULL AND pmid<>''").fetchall())
der_set = set(r[0] for r in con.execute(f"SELECT DISTINCT nct_id FROM {t('study_references')} WHERE reference_type='DERIVED' AND pmid IS NOT NULL AND pmid<>''").fetchall())
rows = con.execute(f"""SELECT o.nct_id, lower(coalesce(o.units,'')) units, TRY_CAST(a.param_value AS DOUBLE) md
 FROM {t('outcomes')} o JOIN {t('outcome_analyses')} a ON a.outcome_id = o.id JOIN t2dm d ON o.nct_id = d.nct_id
 WHERE (lower(o.title) LIKE '%hba1c%' OR lower(o.title) LIKE '%hemoglobin a1c%' OR lower(o.title) LIKE '%glycated%'
        OR lower(o.title) LIKE '%glycosylated hemoglobin%' OR lower(o.title) LIKE '%hemoglobin a1%')
   AND lower(coalesce(a.param_type,'')) LIKE '%mean difference%' AND a.param_value IS NOT NULL;""").fetchall()
con.execute(f"""CREATE TEMP TABLE iv AS SELECT nct_id, lower(name) nm FROM {t('interventions')} WHERE nct_id IN (SELECT nct_id FROM t2dm);""")
names = {}
for nct, nm in con.execute("SELECT nct_id, nm FROM iv").fetchall():
    names.setdefault(nct, []).append(nm or "")


def classes_of(nct):
    s = " ".join(names.get(nct, []))
    return [c for c, kws in CLASSES.items() if any(k in s for k in kws)]


recs = []   # (nct, class, amd)
for nct, units, md in rows:
    f = 0.0915 if ('mmol/mol' in units or 'mmol / mol' in units) else 1.0
    amd = abs(md * f)
    if not np.isfinite(amd) or amd > 5:
        continue
    for c in classes_of(nct):
        recs.append((nct, c, amd))


def compute(pub_pred):
    per = {c: {'pub': [], 'reg': []} for c in CLASSES}
    for nct, c, amd in recs:
        per[c]['pub' if pub_pred(nct) else 'reg'].append(amd)
    xs, ys, ws = [], [], []
    for c in CLASSES:
        p = np.array(per[c]['pub']); r = np.array(per[c]['reg'])
        if len(p) >= 8 and len(r) >= 8 and c in LAM:
            xs.append(1 - LAM[c]); ys.append(p.mean() / r.mean() - 1.0); ws.append(min(len(p), len(r)))
    xs, ys, ws = map(np.array, (xs, ys, ws))
    kp = float(np.sum(ws * np.maximum(0, ys)) / np.sum(ws))
    corr = float(np.corrcoef(xs, ys)[0, 1]) if len(xs) > 2 else float('nan')
    return dict(kappa_pooled=kp, corr=corr, n_classes=int(len(xs)))


defs = {
    'both (main: DERIVED or RESULT)': lambda n: n in res_set or n in der_set,
    'RESULT only (stricter)': lambda n: n in res_set,
    'DERIVED only (NLM auto)': lambda n: n in der_set,
}
print("=" * 78)
print("Sensitivity of the external magnitude to the 'published' definition")
print("=" * 78)
print(f"  {'definition':34}{'n_classes':>10}{'kappa_pooled':>14}{'corr':>8}")
out = {}
for name, pred in defs.items():
    r = compute(pred)
    out[name] = r
    print(f"  {name:34}{r['n_classes']:>10}{r['kappa_pooled']:>14.4f}{r['corr']:>8.3f}")
kps = [v['kappa_pooled'] for v in out.values()]
corrs = [v['corr'] for v in out.values()]
print(f"\n  kappa_pooled range [{min(kps):.3f}, {max(kps):.3f}]  |  corr range [{min(corrs):.3f}, {max(corrs):.3f}]")
stable = (max(kps) - min(kps) < 0.10) and (min(corrs) > 0.3)
print(f"  VERDICT: {'STABLE across definitions (kappa within 0.10, corr>0.3 all)' if stable else 'sensitive -- report the spread'}")
json.dump(out, open(HERE / "aact_kappa_sensitivity_result.json", "w"), indent=1)
print("wrote aact_kappa_sensitivity_result.json")
