"""test_drma.py -- validate the from-scratch DRMA engine against dosresmeta 2.2.0.

Gold numbers live in doseresponse/reference/ref_linear.json and ref_spline.json,
generated by ref_fit.R / ref_spline.R on the canonical alcohol_crc JSS dataset.
Run:  PYTHONPATH=doseresponse python -m pytest doseresponse/test_drma.py -q
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import drma

REF = Path(__file__).resolve().parent / "reference"
DATA = pd.read_csv(REF / "alcohol_crc.csv")
KNOTS = None  # filled from ref_spline.json


def _load(name):
    with open(REF / name) as f:
        return json.load(f)


# --------------------------------------------------------------------------- #
def test_gl_covariance_study1():
    """GL covariance reconstruction matches dosresmeta::covar.logrr exactly."""
    ref = _load("ref_linear.json")
    Sref = np.array(ref["study1_cov"], float)
    g = DATA[DATA["id"] == "atm"]
    S = drma.gl_covariance(g["logrr"].to_numpy(float), g["se"].to_numpy(float) ** 2,
                           g["cases"].to_numpy(float), g["peryears"].to_numpy(float), "ir")
    assert np.allclose(S, Sref, atol=1e-8, rtol=0), np.abs(S - Sref).max()


def test_gl_adjusted_counts_study1():
    ref = _load("ref_linear.json")
    Aref = np.array(ref["study1_adjA"], float)
    g = DATA[DATA["id"] == "atm"]
    A, _ = drma.gl_reconstruct(g["logrr"].to_numpy(float), g["se"].to_numpy(float) ** 2,
                               g["cases"].to_numpy(float), g["peryears"].to_numpy(float), "ir")
    assert np.allclose(A, Aref, atol=1e-4, rtol=0), np.abs(A - Aref).max()


def test_first_stage_slopes():
    """Per-study first-stage GLS slopes match dosresmeta's b_i."""
    ref = _load("ref_linear.json")
    bi_ref = np.array(ref["bi"], float)
    fit = drma.drma_two_stage(DATA, n_col="peryears", transform="linear", method="fixed")
    bi = fit.bi.ravel()
    assert np.allclose(bi, bi_ref, atol=1e-7, rtol=0), np.abs(bi - bi_ref).max()


def test_linear_fixed():
    ref = _load("ref_linear.json")
    fit = drma.drma_two_stage(DATA, n_col="peryears", transform="linear", method="fixed")
    assert abs(float(fit.coef[0]) - ref["linear_fixed_coef"]) < 1e-7
    assert abs(float(np.sqrt(fit.vcov[0, 0])) - ref["linear_fixed_se"]) < 1e-7


def test_linear_reml():
    ref = _load("ref_linear.json")
    fit = drma.drma_two_stage(DATA, n_col="peryears", transform="linear", method="reml")
    assert abs(float(fit.coef[0]) - ref["linear_reml_coef"]) < 1e-6
    assert abs(float(np.sqrt(fit.vcov[0, 0])) - ref["linear_reml_se"]) < 1e-6
    # tau2 (Psi) is ~0 in this dataset; REML must agree
    assert float(fit.Psi[0, 0]) < 1e-6


def test_predict_logrr_defaults_to_fit_ref_dose():
    """Regression (P1-3): predict_logrr must default ref_dose to the fit's own
    reference dose, not 0. Built here with a NONZERO ref (the canonical
    alcohol_crc reference dose happens to be 0, which masked the bug)."""
    fit = drma.DRMAFit(
        coef=np.array([0.5]), vcov=np.array([[0.01]]), Psi=np.array([[0.0]]),
        method="fixed", bi=np.array([[0.5]]), Sigma_list=[np.array([[0.01]])],
        knots=None, transform="linear", ref_dose=3.0, loglik=float("nan"))
    # default ref_dose -> uses fit.ref_dose=3.0, so logRR(3 vs 3) == 0
    yhat, _ = drma.predict_logrr(fit, 3.0)
    assert abs(float(np.ravel(yhat)[0])) < 1e-9, yhat
    # the OLD default (0.0) would predict logRR(3 vs 0) = 3*0.5 = 1.5 != 0
    yhat0, _ = drma.predict_logrr(fit, 3.0, ref_dose=0.0)
    assert abs(float(np.ravel(yhat0)[0]) - 1.5) < 1e-9, yhat0


def test_rcs_basis_validates_knots():
    """Regression (P1-6): rcs_basis must reject non-finite, duplicate, or
    unsorted knots. Duplicates make denom=0 (nan basis); an unsorted sequence
    silently builds the wrong basis. Fail closed instead."""
    x = np.array([1.0, 2.0, 3.0])
    for bad in ([1.0, 2.0, 2.0],          # duplicate -> denom 0 -> nan
                [4.0, 1.0, 2.0],          # unsorted  -> wrong boundary knots
                [1.0, float("nan"), 3.0],  # non-finite
                [1.0, 2.0, float("inf")]):
        with pytest.raises(ValueError):
            drma.rcs_basis(x, bad)
    # a valid strictly-increasing knot vector still works and is finite
    B = drma.rcs_basis(x, [1.0, 2.0, 3.0])
    assert np.all(np.isfinite(B))


def test_mvmeta_k1_reduces_to_fixed_effect():
    """Regression (P0-2): REML cannot identify between-study covariance from a
    SINGLE study — the REML profile is flat in Psi at k=1 (log|S+Psi| and
    log|A| = -log|S+Psi| cancel, quad=0), so the optimizer returned an arbitrary
    start-dependent Psi (~avg_within/2) that spuriously inflated the SE (0.026 vs
    the correct fixed 0.021). k=1 must reduce to the fixed-effect (Psi=0) limit."""
    bi = np.array([[0.5]])
    Slist = [np.array([[0.021 ** 2]])]
    beta, Vbeta, Psi, ll = drma.mvmeta(bi, Slist, method="reml")
    assert float(np.ravel(Psi)[0]) == 0.0, Psi                 # no between-study var
    assert abs(float(np.sqrt(np.ravel(Vbeta)[0])) - 0.021) < 1e-9
    # matches the fixed-effect fit exactly
    b_f, V_f, P_f, _ = drma.mvmeta(bi, Slist, method="fixed")
    assert abs(float(np.ravel(Vbeta)[0]) - float(np.ravel(V_f)[0])) < 1e-12


# --- spline (multivariate p=2) -------------------------------------------- #
def _spline_fit(method):
    ref = _load("ref_spline.json")
    knots = np.array(ref["knots"], float)
    return drma.drma_two_stage(DATA, n_col="peryears", transform="rcs",
                               knots=knots, method=method), ref


def test_rcs_basis_value():
    ref = _load("ref_spline.json")
    knots = np.array(ref["knots"], float)
    B = drma.rcs_basis(np.array([25.0]), knots).ravel()
    assert np.allclose(B, np.array(ref["basis_dose25"], float), atol=1e-8)


def test_spline_fixed():
    fit, ref = _spline_fit("fixed")
    assert np.allclose(fit.coef, np.array(ref["spline_fixed_coef"], float),
                       atol=1e-7, rtol=0), np.abs(fit.coef - np.array(ref["spline_fixed_coef"])).max()
    Vref = np.array(ref["spline_fixed_vcov"], float)
    assert np.allclose(fit.vcov, Vref, atol=1e-9, rtol=0), np.abs(fit.vcov - Vref).max()


def test_spline_reml():
    fit, ref = _spline_fit("reml")
    cref = np.array(ref["spline_reml_coef"], float)
    assert np.allclose(fit.coef, cref, atol=1e-5, rtol=0), np.abs(fit.coef - cref).max()
    Psiref = np.array(ref["spline_reml_Psi"], float)
    assert np.allclose(fit.Psi, Psiref, atol=1e-5, rtol=0), np.abs(fit.Psi - Psiref).max()


def test_one_stage_vs_two_stage_fixed_linear():
    """One-stage pooled GLS == two-stage fixed for linear (algebraic identity)."""
    f1 = drma.drma_one_stage(DATA, n_col="peryears", transform="linear")
    f2 = drma.drma_two_stage(DATA, n_col="peryears", transform="linear", method="fixed")
    assert abs(float(f1.coef[0]) - float(f2.coef[0])) < 1e-9


if __name__ == "__main__":
    import sys
    sys.exit(pytest.main([__file__, "-q"]))
